/** English gallery/card alts keyed by image src. */
export const galleryAltEnBySrc: Record<string, string> = {
  "/assets/residenziale/architettura-bergamo.webp": "Architectural volumes of the private steel residence in Veneto",
  "/assets/residenziale/ingegneria-civile-brescia.webp": "Steel structure erection for the residential villa in Veneto",
  "/assets/residenziale/ingegneria-urbanistica.webp": "Integrated steel villa design with landscape insertion in Veneto",
  "/assets/residenziale/progettazione-strutture-acciaio.webp": "Interiors with steel frame and large spans in the private Veneto residence",
  "/assets/residenziale/progettazione-strutture-acciaio-franciacorta.webp": "Construction detail of the steel load-bearing structure — Veneto residence",
  "/assets/residenziale/strutture-acciaio-bergamo.webp": "Steelwork during construction of the steel villa in Veneto",
  "/assets/residenziale/studio-ingegneria-architettura-adro.webp": "Construction site of the private steel residence in Veneto",
  "/assets/residenziale/villa-acciaio-lusso.webp": "Overview of the steel structure integrated into the Veneto landscape",
  "/assets/residenziale/villa-acciaio-salsomaggiore/scavo-fondazioni-villa-acciaio-salsomaggiore.webp": "Excavation and ground preparation for foundations — steel villa in Salsomaggiore Terme (PR)",
  "/assets/residenziale/villa-acciaio-salsomaggiore/fondazioni-su-pali-villa-acciaio.webp": "Concrete pour for pile foundations — steel villa in Salsomaggiore Terme",
  "/assets/residenziale/villa-acciaio-salsomaggiore/murature-cemento-armato-seminterrato.webp": "Reinforced-concrete basement walls and stair core — Salsomaggiore Terme",
  "/assets/residenziale/villa-acciaio-salsomaggiore/cantiere-villa-acciaio-salsomaggiore.webp": "Site view with reinforced-concrete foundations — steel villa in Salsomaggiore Terme",
  "/assets/residenziale/villa-acciaio-salsomaggiore/carpenteria-metallica-villa-acciaio.webp": "Erection of the load-bearing steel frame — steel villa in Salsomaggiore Terme",
  "/assets/residenziale/villa-acciaio-salsomaggiore/struttura-acciaio-copertura-fotovoltaico.webp": "Steel roof structure prepared for photovoltaic panels — Salsomaggiore Terme",
  "/assets/residenziale/villa-acciaio-salsomaggiore/pareti-a-secco-lana-minerale-villa.webp": "Dry-wall installation with mineral-wool insulation — steel villa in Salsomaggiore Terme",
  "/assets/residenziale/villa-acciaio-salsomaggiore/finiture-interne-cartongesso-villa-acciaio.webp": "Interior plasterboard finishes with services installation — steel villa in Salsomaggiore Terme",
  "/assets/residenziale/villa-acciaio-salsomaggiore/finiture-esterne-terrazzo-villa-acciaio.webp": "External finishes and setting-out on the cantilever terrace — steel villa in Salsomaggiore Terme",
  "/assets/industriale/capannone-erbusco/capannone-industriale-erbusco.webp": "Exterior view of the industrial steel building in Erbusco (Brescia)",
  "/assets/industriale/capannone-erbusco/progettazione-strutture-adro.webp": "Structural design of the steel-framed industrial building — Erbusco (BS)",
  "/assets/industriale/capannone-erbusco/strutture-industriali-erbusco.webp": "Load-bearing steel frame of the industrial building in Erbusco",
  "/assets/industriale/capannone-erbusco/vista-capannone-erbusco.webp": "Overview of the steel production extension — industrial building in Erbusco (BS)",
  "/assets/industriale/capannone-erbusco/strutture-industriali.webp": "Detail of beams and structural connections in the Erbusco industrial building",
  "/assets/industriale/capannone-erbusco/ingegneria-civile-adro.webp": "Interior of the industrial building with structure designed for overhead cranes — Erbusco (BS)",
  "/assets/industriale/ampliamento-complesso-zootecnico/capriate-metalliche-grande-luce-complesso-zootecnico.webp": "Long-span steel trusses under erection — livestock complex extension",
  "/assets/industriale/ampliamento-complesso-zootecnico/carpenteria-metallica-basamento-cemento-zootecnico.webp": "Steelwork on a reinforced-concrete base — livestock complex extension",
  "/assets/industriale/ampliamento-complesso-zootecnico/vista-aerea-ampliamento-complesso-zootecnico.webp": "Aerial view of new steel trusses integrated with existing structures — livestock complex",
  "/assets/industriale/centro-direzionale-provaglio-diseo/vista-generale-soppalco-centro-direzionale-provaglio-diseo.webp": "Overall view of the steel mezzanine integrated into the existing building — Provaglio d'Iseo (BS)",
  "/assets/industriale/centro-direzionale-provaglio-diseo/carpenteria-metallica-soppalco-provaglio-diseo.webp": "Steel mezzanine erection with structural connections and metal decking — Provaglio d'Iseo office centre (BS)",
  "/assets/industriale/centro-direzionale-provaglio-diseo/progettazione-strutture-acciaio-industriali.jpeg": "Roof opening and steelwork on the mezzanine level — Provaglio d'Iseo office centre (BS)",
  "/assets/industriale/centro-direzionale-provaglio-diseo/strutture-in-acciaio-soppalco-direzionale.jpeg": "Steel beams and trusses integrated into the existing structure — Provaglio d'Iseo mezzanine (BS)",
  "/assets/industriale/centro-direzionale-provaglio-diseo/vista-copertura-progettazione-acciaio.jpeg": "Underside view of the steel framing under erection — Provaglio d'Iseo office centre (BS)",
  "/assets/superstudio-village-entrata-esterno.webp": "External entrance of the Superstudio Village complex in Milan Bovisa",
  "/assets/superstudio-village-struttura-acciaio.webp": "Detail of the prefabricated steel structure — Superstudio Village Milan",
  "/assets/superstudio-village-vista-della-struttura.webp": "Facade and volumes of the Superstudio Village complex in Milan Bovisa",
  "/assets/superstudio-village-pavimentazione-interni.webp": "Flooring and finishes of the interior spaces — Superstudio Village Milan",
  "/assets/superstudio-village-ricerca-innovazione.webp": "Exterior render of the Superstudio Village complex in Milan Bovisa",
  "/assets/superstudio-village-innovazione-tecnologica.webp": "Projection hall with load-bearing structure — Superstudio Village Milan",
  "/assets/superstudio-village-acciaio-pre-fabbricato.webp": "Erection of the internal steel structure — Superstudio Village Milan",
  "/assets/superstudio-village-eventi.webp": "Event hall of the Superstudio Village complex in Milan Bovisa",
  "/assets/superstudio-village-sala-proiezione.webp": "Projection hall with steel roof structure — Superstudio Village Milan",
  "/assets/superstudio-maxi/antincendio-adro.webp": "Interior lounge of the Superstudio Maxi complex in Milan Famagosta",
  "/assets/superstudio-maxi/strutture-acciaio-lombardia.webp": "Exterior view of the industrial building reuse — Superstudio Maxi Famagosta",
  "/assets/superstudio-maxi/ingegneria-urbanistica-franciacorta.webp": "Interior area with strengthened structures — Superstudio Maxi Milan",
  "/assets/superstudio-maxi/progettazione-industriale-ricettivo.webp": "Flooring of the exhibition spaces — Superstudio Maxi Famagosta",
  "/assets/superstudio-maxi/sicurezza-cantieri-franciacorta.webp": "Exterior render of the Superstudio Maxi complex in Milan Famagosta",
  "/assets/superstudio-maxi/strutture-acciaio-milano.webp": "Projection hall with new steel structure — Superstudio Maxi Milan",
  "/assets/superstudio-maxi/studio-ingegneria-brescia.webp": "Internal structural detail of the Superstudio Maxi complex in Milan",
  "/assets/superstudio-maxi/strutture-acciaio-milano-brescia.webp": "Event hall with steel roof — Superstudio Maxi Famagosta",
  "/assets/superstudio-maxi/architettura-urbanistica-brescia.webp": "Projection hall of the Superstudio Maxi complex in Milan Famagosta",
};
